//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonT()
        {
            this.DichVuDaDats = new HashSet<DichVuDaDat>();
        }
    
        public int maHDTS { get; set; }
        public Nullable<System.DateTime> ngayThueSan { get; set; }
        public Nullable<int> tienSan { get; set; }
        public Nullable<int> tongTien { get; set; }
        public Nullable<int> tiendichvu { get; set; }
        public Nullable<int> maPT { get; set; }
        public Nullable<int> maNV { get; set; }
        public Nullable<int> maTinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVuDaDat> DichVuDaDats { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhieuThueSan PhieuThueSan { get; set; }
        public virtual tinhTrangHD tinhTrangHD { get; set; }
    }
}
