//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QlyTheThaoEntities : DbContext
    {
        public QlyTheThaoEntities()
            : base("name=QlyTheThaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<DichVuDaDat> DichVuDaDats { get; set; }
        public virtual DbSet<HoaDonT> HoaDonTS { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiSan> LoaiSans { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuThueSan> PhieuThueSans { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<San> Sans { get; set; }
        public virtual DbSet<SuKien> SuKiens { get; set; }
        public virtual DbSet<tinhTrangHD> tinhTrangHDs { get; set; }
        public virtual DbSet<tinhTrangPT> tinhTrangPTs { get; set; }
        public virtual DbSet<TinhTrangSan> TinhTrangSans { get; set; }
        public virtual DbSet<TinNhan> TinNhans { get; set; }
    }
}
