//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.HoaDonTS = new HashSet<HoaDonT>();
            this.PhieuThueSans = new HashSet<PhieuThueSan>();
        }
    
        public int maNV { get; set; }
        public string hotenNV { get; set; }
        public string emailNV { get; set; }
        public string sdtNV { get; set; }
        public string diaChiNV { get; set; }
        public Nullable<System.DateTime> dobNV { get; set; }
        public string taiKhoan { get; set; }
        public string matKhau { get; set; }
        public Nullable<int> maPH { get; set; }
        public Nullable<int> maCV { get; set; }
        public Nullable<int> maSK { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonT> HoaDonTS { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        public virtual SuKien SuKien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuThueSan> PhieuThueSans { get; set; }
    }
}
