//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThueSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuThueSan()
        {
            this.HoaDonTS = new HashSet<HoaDonT>();
        }
    
        public int maPT { get; set; }
        public Nullable<int> soGioThue { get; set; }
        public Nullable<System.DateTime> NgayThue { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> maSan { get; set; }
        public Nullable<int> maNV { get; set; }
        public string maKH { get; set; }
        public Nullable<int> maTinhTrang { get; set; }
        public string thong_tin_khach_hang_thue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonT> HoaDonTS { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual San San { get; set; }
        public virtual tinhTrangPT tinhTrangPT { get; set; }
    }
}
