//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class San
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public San()
        {
            this.PhieuThueSans = new HashSet<PhieuThueSan>();
        }
    
        public int maSan { get; set; }
        public string maSoSan { get; set; }
        public Nullable<int> Loai_San { get; set; }
        public Nullable<int> maTinhTrang { get; set; }
    
        public virtual LoaiSan LoaiSan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuThueSan> PhieuThueSans { get; set; }
        public virtual TinhTrangSan TinhTrangSan { get; set; }
    }
}
